name: App
options:
  bundleIdPrefix: com.ryo.swiftui-atom-properties.examples
  createIntermediateGroups: true
settingGroups:
  app:
    CODE_SIGNING_REQUIRED: NO
    CODE_SIGN_IDENTITY: "-"
    CODE_SIGN_STYLE: Manual
    OTHER_SWIFT_FLAGS:
      - -Xfrontend
      - -enable-actor-data-race-checks

targetTemplates:
  App:
    type: application
    info:
      path: App/Info-${target_name}.plist
      properties:
        UILaunchScreen:
        UIRequiresFullScreen: true
        CFBundleDisplayName: Atoms
        NSLocationWhenInUseUsageDescription: Example Usage
        NSMicrophoneUsageDescription: Example Usage
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
    settings:
      groups:
        - app

schemes:
  iOS:
    build:
      targets:
        iOS: all

packages:
  iOSApp:
    path: Packages/iOS

  CrossPlatformApp:
    path: Packages/CrossPlatform

targets:
  iOS:
    templates:
      - App
    platform: iOS
    deploymentTarget: 16.0
    dependencies:
      - package: iOSApp
    sources:
      - App/iOS.swift

  CrossPlatform:
    templates:
      - App
    platform:
      - iOS
      - macOS
      - tvOS
    deploymentTarget:
      iOS: 14.0
      macOS: 11.0
      tvOS: 14.0
    dependencies:
      - package: CrossPlatformApp
    sources:
      - App/CrossPlatform.swift
